### ISSUE TITLE
Unable to click through menu

### ISSUE THREAD

**Issue by martinstolz** [tonyarnold/Xcode-4-Uncrustify-Automator-Services#4]
Hey, thanks for your shared services!

I got all working but not the Re-Indent service. After some testing I figured out that the menu click code doesn't work. I also tried the common longer way which the 'menu_click' method tries to wrap. No success.

When using this service an error occurs: "The action "Run AppleScript" encountered an error"

Could it be an issue with Lion 10.7.3?

**Comment by tonyarnold** [comment]
Hi @martinstolz, do you have 'Enable access for assistive devices' enabled in the 'Universal Access' system preferences?

**Comment by martinstolz** [comment]
This was strange. It was activated but it didn't work. Then I unhooked it, tried again. Got the error which was expectable. Then hooked again and it worked.

Thanks again.

**Comment by tonyarnold** [comment]
Thanks for letting me know, @martinstolz. These scripts have always been a little hard to get going in the first instance, but I use them very frequently throughout my work day, so hopefully they'll be stable and trouble-free for you from here on out!
